### ISSUE TITLE
据说你写了个chrome同步插件  那个导入功能怎么实现的啊？

### ISSUE THREAD

**Issue by zhenruyan** [adeweb/adeweb.github.io#1]
如题   chrome.bookmarks.crate()只能生成一个。  chrome.bookmarks.import只能自带的扩展用

**Comment by adeweb** [comment]
没考虑导入功能，手动也方便。不过也是有思路的，解析导入文件，批量创建？

**Comment by zhenruyan** [comment]
需要一直遍历然后一个一个创建///  好累
